
package com.diestel.ws;

import com.diestel.ws.*;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PxUniversalSoap", targetNamespace = "http://www.pagoexpress.com.mx/pxUniversal")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PxUniversalSoap {


    /**
     * Solicitud de informacion de un producto
     * 
     * @param cArrayCampos
     * @return
     *     returns com.diestel.ws.ArrayOfCCampo
     */
    @WebMethod(operationName = "Info", action = "http://www.pagoexpress.com.mx/pxUniversal/Info")
    @WebResult(name = "InfoResult", targetNamespace = "http://www.pagoexpress.com.mx/pxUniversal")
    @RequestWrapper(localName = "Info", targetNamespace = "http://www.pagoexpress.com.mx/pxUniversal", className = "com.diestel.ws.Info")
    @ResponseWrapper(localName = "InfoResponse", targetNamespace = "http://www.pagoexpress.com.mx/pxUniversal", className = "com.diestel.ws.InfoResponse")
    public ArrayOfCCampo info(
        @WebParam(name = "cArrayCampos", targetNamespace = "http://www.pagoexpress.com.mx/pxUniversal")
        ArrayOfCCampo cArrayCampos);

    /**
     * Aplicacion de peticion sobre el producto seleccionado
     * 
     * @param cArrayCampos
     * @return
     *     returns com.diestel.ws.ArrayOfCCampo
     */
    @WebMethod(operationName = "Ejecuta", action = "http://www.pagoexpress.com.mx/pxUniversal/Ejecuta")
    @WebResult(name = "EjecutaResult", targetNamespace = "http://www.pagoexpress.com.mx/pxUniversal")
    @RequestWrapper(localName = "Ejecuta", targetNamespace = "http://www.pagoexpress.com.mx/pxUniversal", className = "com.diestel.ws.Ejecuta")
    @ResponseWrapper(localName = "EjecutaResponse", targetNamespace = "http://www.pagoexpress.com.mx/pxUniversal", className = "com.diestel.ws.EjecutaResponse")
    public ArrayOfCCampo ejecuta(
        @WebParam(name = "cArrayCampos", targetNamespace = "http://www.pagoexpress.com.mx/pxUniversal")
        ArrayOfCCampo cArrayCampos);

    /**
     * Aplicacion de reverso sobre el producto seleccionado
     * 
     * @param cArrayCampos
     * @return
     *     returns com.diestel.ws.ArrayOfCCampo
     */
    @WebMethod(operationName = "Reversa", action = "http://www.pagoexpress.com.mx/pxUniversal/Reversa")
    @WebResult(name = "ReversaResult", targetNamespace = "http://www.pagoexpress.com.mx/pxUniversal")
    @RequestWrapper(localName = "Reversa", targetNamespace = "http://www.pagoexpress.com.mx/pxUniversal", className = "com.diestel.ws.Reversa")
    @ResponseWrapper(localName = "ReversaResponse", targetNamespace = "http://www.pagoexpress.com.mx/pxUniversal", className = "com.diestel.ws.ReversaResponse")
    public ArrayOfCCampo reversa(
        @WebParam(name = "cArrayCampos", targetNamespace = "http://www.pagoexpress.com.mx/pxUniversal")
        ArrayOfCCampo cArrayCampos);

    /**
     * Prueba de conexion al Web Service
     * 
     * @return
     *     returns com.diestel.ws.ArrayOfCCampo
     */
    @WebMethod(operationName = "Test", action = "http://www.pagoexpress.com.mx/pxUniversal/Test")
    @WebResult(name = "TestResult", targetNamespace = "http://www.pagoexpress.com.mx/pxUniversal")
    @RequestWrapper(localName = "Test", targetNamespace = "http://www.pagoexpress.com.mx/pxUniversal", className = "com.diestel.ws.Test")
    @ResponseWrapper(localName = "TestResponse", targetNamespace = "http://www.pagoexpress.com.mx/pxUniversal", className = "com.diestel.ws.TestResponse")
    public ArrayOfCCampo test();

}
