
package test;

import com.diestel.ws.*;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PxUniversal", targetNamespace = "http://www.pagoexpress.com.mx/pxUniversal", wsdlLocation = "https://www.integracionesqapx.com.mx/wsUniversal/pxuniversal.asmx?wsdl")
public class PxUniversal
    extends Service
{

    private final static URL PXUNIVERSAL_WSDL_LOCATION;
    private final static WebServiceException PXUNIVERSAL_EXCEPTION;
    private final static QName PXUNIVERSAL_QNAME = new QName("http://www.pagoexpress.com.mx/pxUniversal", "PxUniversal");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://www.integracionesqapx.com.mx/wsUniversal/pxuniversal.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PXUNIVERSAL_WSDL_LOCATION = url;
        PXUNIVERSAL_EXCEPTION = e;
    }

    public PxUniversal() {
        super(__getWsdlLocation(), PXUNIVERSAL_QNAME);
    }

    public PxUniversal(WebServiceFeature... features) {
        super(__getWsdlLocation(), PXUNIVERSAL_QNAME, features);
    }

    public PxUniversal(URL wsdlLocation) {
        super(wsdlLocation, PXUNIVERSAL_QNAME);
    }

    public PxUniversal(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PXUNIVERSAL_QNAME, features);
    }

    public PxUniversal(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PxUniversal(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PxUniversalSoap
     */
    @WebEndpoint(name = "PxUniversalSoap")
    public PxUniversalSoap getPxUniversalSoap() {
        return super.getPort(new QName("http://www.pagoexpress.com.mx/pxUniversal", "PxUniversalSoap"), PxUniversalSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PxUniversalSoap
     */
    @WebEndpoint(name = "PxUniversalSoap")
    public PxUniversalSoap getPxUniversalSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.pagoexpress.com.mx/pxUniversal", "PxUniversalSoap"), PxUniversalSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns PxUniversalSoap
     */
    @WebEndpoint(name = "PxUniversalSoap12")
    public PxUniversalSoap getPxUniversalSoap12() {
        return super.getPort(new QName("http://www.pagoexpress.com.mx/pxUniversal", "PxUniversalSoap12"), PxUniversalSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PxUniversalSoap
     */
    @WebEndpoint(name = "PxUniversalSoap12")
    public PxUniversalSoap getPxUniversalSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.pagoexpress.com.mx/pxUniversal", "PxUniversalSoap12"), PxUniversalSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns PxUniversalHttpPost
     */
    @WebEndpoint(name = "PxUniversalHttpPost")
    public PxUniversalHttpPost getPxUniversalHttpPost() {
        return super.getPort(new QName("http://www.pagoexpress.com.mx/pxUniversal", "PxUniversalHttpPost"), PxUniversalHttpPost.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PxUniversalHttpPost
     */
    @WebEndpoint(name = "PxUniversalHttpPost")
    public PxUniversalHttpPost getPxUniversalHttpPost(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.pagoexpress.com.mx/pxUniversal", "PxUniversalHttpPost"), PxUniversalHttpPost.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PXUNIVERSAL_EXCEPTION!= null) {
            throw PXUNIVERSAL_EXCEPTION;
        }
        return PXUNIVERSAL_WSDL_LOCATION;
    }

}
